pub mod esef_taxonomy;

use anyhow::Result;
use crate::aggregation::AggregationResult;

pub struct IxbrlGenerator;

impl IxbrlGenerator {
    pub fn generate_xhtml(aggregation: &AggregationResult) -> Result<String> {
        let xhtml = format!(
            r#"<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ix="http://www.xbrl.org/2013/inlineXBRL">
<head>
    <meta charset="UTF-8" />
    <title>Targoo V2 - ESEF/CSRD Report</title>
    <style>
        body {{ font-family: sans-serif; }}
        table {{ border-collapse: collapse; width: 100%; }}
        th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
        th {{ background-color: #f2f2f2; }}
    </style>
</head>
<body>
    <h1>GHG Emissions Report (iXBRL MVP)</h1>
    <p>Generated by Targoo V2 ESG Data Refinery</p>
    <table>
        <tr>
            <th>Scope</th>
            <th>tCO2e</th>
        </tr>
        <tr>
            <td>Scope 1</td>
            <td><ix:nonNumeric name="esrs:Scope1Emissions">{:.2}</ix:nonNumeric></td>
        </tr>
        <tr>
            <td>Scope 2 (Location-Based)</td>
            <td><ix:nonNumeric name="esrs:Scope2Emissions">{:.2}</ix:nonNumeric></td>
        </tr>
        <tr>
            <td>Scope 3</td>
            <td><ix:nonNumeric name="esrs:Scope3Emissions">{:.2}</ix:nonNumeric></td>
        </tr>
        <tr>
            <td><strong>TOTAL</strong></td>
            <td><strong><ix:nonNumeric name="esrs:TotalEmissions">{:.2}</ix:nonNumeric></strong></td>
        </tr>
    </table>
</body>
</html>"#,
            aggregation.scope1_tco2e,
            aggregation.scope2_lb_tco2e,
            aggregation.scope3_tco2e,
            aggregation.total_tco2e
        );

        Ok(xhtml)
    }
}
